# date: 10/15/2024
# author: Yuezhe Li 
# purpose of this code: combine ADC tox on myelocyte and CFU-MK

rm(list=ls())  #Clear out existing objects
gc()

library(here)
library(tidyverse)
library(mrgsolve)
library(gridExtra)

mod <- mread("model/human_mep_lymp_neut_adc")

ss <- mod  %>% init(LT0 = 1275) %>% mrgsim(end = 365*7) %>% as_tibble() %>% select(-c(ID, time)) %>% tail(n = 1)

BW = 70
dose_mgkg = 3.6
MW_ADC = 15E4
Vplasma = param(mod)$Vcent

#=============================== T-DM1 simulation ===============================#

mod2 <- mod %>% init(ss) %>% param(IC50_adc_myelocyte = param(mod)$IC50_adc_cfumk) %>% param(tauPlatelet = 3, kMKplatelet = 500, IC50_adc_cfumk = 10, IC50_adc_myelocyte = 10)

# observed data obtained from Girish et al., 2012; # https://link.springer.com/article/10.1007/s00280-011-1817-3
obs = data.frame(
  time_day = c(0.1,0.25,1,2,3,0.1,0.25,1,2,3,7,0.1,0.25,1,2,3,7,0.25,1,2,3,7,10,14,17,21,0.1,0.25,1,2,3,7,10,17,21,0.1,0.25,1,2,3,7,14,17,21), 
  T_DM1_ugperml = c(9.66134,7.1674,4.22606,2.54967,1.11527,13.02307,10.35053,7.33393,5.69654,1.37138,0.52264,20.14835,20.14835,11.08888,7.33393,3.208,0.49918,74.61359,55.35313,45.01597,33.39572,17.15592,10.35053,3.68201,2.02644,0.40596,74.61359,66.51853,48.22717,34.96559,27.15909,13.95206,9.44196,2.27305,0.77229,126.54482,118.11885,89.66407,78.12105,65.00812,29.09648,12.43836,7.1674,3.3588),
  Dose_mgkg = c(0.3,0.3,0.3,0.3,0.3,0.6,0.6,0.6,0.6,0.6,0.6,1.2,1.2,1.2,1.2,1.2,1.2,2.4,2.4,2.4,2.4,2.4,2.4,2.4,2.4,2.4,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,3.6,4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.8,4.8)
) %>% 
  mutate(tdm1_nM = T_DM1_ugperml*1E6/MW_ADC)

sim_point3<- mod2 %>% param(base_sTAA = 3) %>% ev(amt = 0.3*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 
sim_point6<- mod2 %>% param(base_sTAA = 3) %>% ev(amt = 0.6*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 
sim_1point2<- mod2 %>% param(base_sTAA = 4) %>% ev(amt = 1.2*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 
sim_2point4<- mod2 %>% param(base_sTAA = 1.16) %>% ev(amt = 2.4*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 
sim_3point6<- mod2 %>% param(base_sTAA = 1) %>% ev(amt = 3.6*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 
sim_4point8<- mod2 %>% param(base_sTAA = 0.1) %>% ev(amt = 4.8*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 

sim2 <- rbind(
  sim_point3 %>% mutate(Dose_mgkg = 0.3),
  sim_point6 %>% mutate(Dose_mgkg = 0.6),
  sim_1point2 %>% mutate(Dose_mgkg = 1.2),
  sim_2point4 %>% mutate(Dose_mgkg = 2.4),
  sim_3point6 %>% mutate(Dose_mgkg = 3.6),
  sim_4point8 %>% mutate(Dose_mgkg = 4.8)
)

p_pk <- ggplot(data = sim2, aes(x = time, y = adc_central, group = Dose_mgkg, col = as.factor(Dose_mgkg) )) + 
  geom_line() + 
  geom_point(data = obs, aes(x = time_day, y = tdm1_nM, group = Dose_mgkg, col = as.factor(Dose_mgkg))) + 
  scale_x_continuous(breaks = c(0, 7, 14, 21), limits = c(0, 21)) + 
  scale_y_continuous(breaks = c(1, 10, 100, 1000), limits = c(1, 1000), trans = "log10") + 
  theme_bw() + 
  labs(x = "Time (day)", y = "plasma ADC (nM)", col = "Dose (mg/kg)", caption = "Generated by script/radx_tox_platelet_neutrophil.r") 

p_pk

p_platelet <- ggplot(data = sim2, aes(x = time, y = PLTconc, group = Dose_mgkg, col = as.factor(Dose_mgkg) )) + 
  geom_line() + 
  geom_hline(yintercept = 51000, linetype = 2, color = "red", alpha = 0.4) +  # cutoff for severe TCP
  #geom_hline(yintercept = 100000, linetype = 3, color = "blue", alpha = 0.4) +  # cutoff for moderate TCP
  scale_x_continuous(breaks = c(0, 21, 42, 63, 84, 105)) + 
  theme_bw() + 
  theme(legend.position = "bottom") + 
  labs(x = "Time (day)", y = "blood platelet (#/uL)", col = "Dose (mg/kg)", caption = "Generated by script/radx_tox_platelet_neutrophil.r") 

p_platelet


p_neut <- ggplot(data = sim2, aes(x = time, y = Neuconc, group = Dose_mgkg, col = as.factor(Dose_mgkg) )) + 
  geom_line() + 
  geom_hline(yintercept = 500, linetype = 2, color = "red", alpha = 0.4) +  # cutoff for severe neutropenia
  scale_x_continuous(breaks = c(0, 21, 42, 63, 84, 105)) + 
  scale_y_continuous(breaks = c(500, 1000, 1500, 2000, 2500)) + 
  theme_bw() + 
  theme(legend.position = "bottom") + 
  labs(x = "Time (day)", y = "blood neutrophil (#/uL)", col = "Dose (mg/kg)", caption = "Generated by script/radx_tox_platelet_neutrophil.r") 

p_neut

png("deliv/figure/adc-plt-neut-tox-tdm1.png", width = 10, height = 3.25, units = "in",res = 1200)
grid.arrange(p_pk, p_platelet, p_neut, ncol = 3)
dev.off()

#=============================== T-Dxd simulation ===============================#
doi2017 <- read.csv(file="data/doi2017.csv", header = TRUE) %>% mutate(tdxd_nM = T_DXd_ugperml*1E6/MW_ADC)

mod3 <- mread("model/human_mep_lymp_neut_adc_pl") %>% init(ss) %>% param(tauPlatelet = 3, kMKplatelet = 500, 
                                   kdec = 0.00144, 
                                   IC50_adc_cfumk = 194.8, IC50_adc_myelocyte = 498.6 #  https://pubmed.ncbi.nlm.nih.gov/34961908
                                   ) 

sim_tdxd_point8<- mod3 %>% ev(amt = 0.8*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 
sim_tdxd_1point6<- mod3 %>% ev(amt = 1.6*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 
sim_tdxd_3point2<- mod3 %>% ev(amt = 3.2*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 
sim_tdxd_5point4<- mod3 %>% ev(amt = 5.4*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 
sim_tdxd_6point4<- mod3 %>% ev(amt = 6.4*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 
sim_tdxd_8<- mod3 %>% ev(amt = 8*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 

sim3 <- rbind(
  sim_tdxd_point8 %>% mutate(Dose = "0.8mg/kg"),
  sim_tdxd_1point6 %>% mutate(Dose = "1.6mg/kg"),
  sim_tdxd_3point2 %>% mutate(Dose = "3.2mg/kg"),
  sim_tdxd_5point4 %>% mutate(Dose = "5.4mg/kg"),
  sim_tdxd_6point4 %>% mutate(Dose = "6.4mg/kg"),
  sim_tdxd_8 %>% mutate(Dose = "8.0mg/kg")
)

p_pk_tdxd <- ggplot(data = sim3, aes(x = time, y = adc_central, group = Dose, col = Dose )) + 
  geom_line() + 
  geom_point(data = doi2017, aes(x = time_day, y = tdxd_nM, col = Dose)) + 
  scale_x_continuous(breaks = c(0, 21, 42, 63), limits = c(0, 63)) + 
  scale_y_continuous(breaks = c(1, 10, 100, 1000), limits = c(1, 2000), trans = "log10") + 
  theme_bw() + 
  theme(legend.position = "bottom") + 
  labs(x = "Time (day)", y = "plasma ADC (nM)", col = "", caption = "Generated by script/radx_tox_platelet_neutrophil.r") 

p_pk_tdxd

# https://link.springer.com/article/10.1007/s10928-023-09884-6, Fig 5b
doi_2017_pl = data.frame(
  time_day = c(0.27, 2.93, 7.87, 14.91, 22.04, 22.24, 43.07, 42.99, 43.19, 50.32, 56.88, 64.30), 
  dxd_nM = c(16.23, 6.22, 2.95, 1.40, 0.73, 4.90, 1.15, 4.97, 14.61, 5.04, 2.23, 1.22)
)

p_pk_dxd_6point4 <- ggplot(data = sim_tdxd_6point4, aes(x = time, y = pl_central)) + 
  geom_line(aes(col = "sims")) + 
  geom_point(data = doi_2017_pl, aes(x = time_day, y = dxd_nM, col = "Doi et al., 2017")) + 
  theme_bw() + 
  theme(legend.position = "bottom") + 
  scale_y_continuous(limits = c(0.1, 10), trans = "log10") + 
  labs(x = "Time (day)", y = "plasma payload (nM)", col = "", title = "Dose = 6.4mg/kg",caption = "Generated by script/radx_tox_platelet_neutrophil.r") 

p_pk_dxd_6point4

p_pk_dxd_central <- ggplot(data = sim3, aes(x = time, y = pl_central, group = Dose, col = Dose )) + 
  geom_line() + 
  theme_bw() + 
  theme(legend.position = "bottom") + 
  scale_y_continuous(limits = c(0.1, 10), trans = "log10") + 
  labs(x = "Time (day)", y = "plasma payload (nM)", col = "", caption = "Generated by script/radx_tox_platelet_neutrophil.r")

p_pk_dxd_central

p_pk_dxd_peripheral <- ggplot(data = sim3, aes(x = time, y = pl_peripheral, group = Dose, col = Dose )) + 
  geom_line() + 
  theme_bw() + 
  theme(legend.position = "bottom") + 
  scale_y_continuous(limits = c(0.1, 10), trans = "log10") + 
  labs(x = "Time (day)", y = "plasma payload (nM)", col = "", caption = "Generated by script/radx_tox_platelet_neutrophil.r")

p_pk_dxd_peripheral

p_platelet_tdxd <- ggplot(data = sim3, aes(x = time, y = PLTconc, group = Dose, col = Dose )) + 
  geom_line() + 
  geom_hline(yintercept = 51000, linetype = 2, color = "red", alpha = 0.4) +  # cutoff for severe TCP
  #geom_hline(yintercept = 100000, linetype = 3, color = "blue", alpha = 0.4) +  # cutoff for moderate TCP
  scale_x_continuous(breaks = c(0, 21, 42, 63, 84, 105)) + 
  theme_bw() + 
  theme(legend.position = "bottom") + 
  labs(x = "Time (day)", y = "blood platelet (#/uL)", col = "", caption = "Generated by script/radx_tox_platelet_neutrophil.r") 

p_platelet_tdxd

p_neut_tdxd <- ggplot(data = sim3, aes(x = time, y = Neuconc, group = Dose, col = Dose )) + 
  geom_line() + 
  geom_hline(yintercept = 500, linetype = 2, color = "red", alpha = 0.4) +  # cutoff for severe neutropenia
  scale_x_continuous(breaks = c(0, 21, 42, 63, 84, 105)) + 
  scale_y_continuous(breaks = c(500, 1000, 1500, 2000, 2500)) + 
  theme_bw() + 
  theme(legend.position = "bottom") + 
  labs(x = "Time (day)", y = "blood neutrophil (#/uL)", col = "", caption = "Generated by script/radx_tox_platelet_neutrophil.r") 

p_neut_tdxd

png("deliv/figure/adc-tdxd-pk.png", width = 7, height = 7, units = "in",res = 1200)
grid.arrange(p_pk_tdxd, p_pk_dxd_6point4, p_pk_dxd_central, p_pk_dxd_peripheral, ncol = 2)
dev.off()

png("deliv/figure/adc-tdxd-plt-neut-tox.png", width = 7, height = 3.25, units = "in",res = 1200)
grid.arrange(p_platelet_tdxd, p_neut_tdxd, ncol = 2)
dev.off()

#=============================== T-Dxd sensitivity analysis ===============================#
mod_10 <- mod3 %>% param(emax_pl_neut = param(mod3)$emax_pl_neut * 10)
mod_100 <- mod3 %>% param(emax_pl_neut = param(mod3)$emax_pl_neut * 100)
mod_1000 <- mod3 %>% param(emax_pl_neut = param(mod3)$emax_pl_neut * 1000)

sim_10_5point4<- mod_10 %>% ev(amt = 5.4*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 
sim_100_5point4<- mod_100 %>% ev(amt = 5.4*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 
sim_1000_5point4<- mod_1000 %>% ev(amt = 5.4*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 

sim_3 <- rbind(
  sim_tdxd_5point4 %>% mutate(dxd_emax_fold = "1"),
  sim_10_5point4 %>% mutate(dxd_emax_fold = "10"),
  sim_100_5point4 %>% mutate(dxd_emax_fold = "100"),
  sim_1000_5point4 %>% mutate(dxd_emax_fold = "1000")
)

p3_neut_tdxd <- ggplot(data = sim_3, aes(x = time, y = Neuconc, group = dxd_emax_fold, col = dxd_emax_fold )) + 
  geom_line() + 
  geom_hline(yintercept = 500, linetype = 2, color = "red", alpha = 0.4) +  # cutoff for severe neutropenia
  scale_x_continuous(breaks = c(0, 21, 42, 63, 84, 105)) + 
  scale_y_continuous(breaks = c(500, 1000, 1500, 2000, 2500)) + 
  theme_bw() + 
  labs(x = "Time (day)", y = "blood neutrophil (#/uL)", col = "Fold of change, \nDxd-induced myelocyte death rate", caption = "Generated by script/radx_tox_platelet_neutrophil.r") 

p3_neut_tdxd

ggsave("deliv/figure/adc-tdxd-neut-tox-sens.png", p3_neut_tdxd, width = 8, height = 3, units = "in", dpi = 300)

mod_ic50_pl_point1 <- mod3 %>% param(IC50_pl_neut = 0.1)
mod_ic50_pl_1 <- mod3 %>% param(IC50_pl_neut = 1)

sim_ic50_point1_5point4<- mod_ic50_pl_point1 %>% ev(amt = 5.4*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 
sim_ic50_1_5point4<- mod_ic50_pl_1 %>% ev(amt = 5.4*BW*1E-3/MW_ADC/Vplasma*1E9, cmt = "adc_central", ii = 21, until = 21 * 5) %>% mrgsim(end = 21 * 5) %>% as_tibble() 

sim_ic50 <- rbind(
  sim_tdxd_5point4 %>% mutate(ic50_pl_neut = "9.54 nM (default)"),
  sim_ic50_point1_5point4 %>% mutate(ic50_pl_neut = "0.1 nM"),
  sim_ic50_1_5point4 %>% mutate(ic50_pl_neut = "1 nM")
)

p4_neut_tdxd <- ggplot(data = sim_ic50, aes(x = time, y = Neuconc, group = ic50_pl_neut, col = ic50_pl_neut )) + 
  geom_line() + 
  geom_hline(yintercept = 500, linetype = 2, color = "red", alpha = 0.4) +  # cutoff for severe neutropenia
  scale_x_continuous(breaks = c(0, 21, 42, 63, 84, 105)) + 
  scale_y_continuous(breaks = c(500, 1000, 1500, 2000, 2500)) + 
  theme_bw() + 
  labs(x = "Time (day)", y = "blood neutrophil (#/uL)", col = "Dxd IC50 in neurtrophil \nand progenitors", caption = "Generated by script/radx_tox_platelet_neutrophil.r") 

p4_neut_tdxd
