# date: 10/11/2024
# author: Yuezhe Li 
# purpose of this code: to fit for ADC tox on neutrophil progenitor in vitro 

rm(list=ls())  #Clear out existing objects
gc()

library(here)
library(tidyverse)
library(mrgsolve)
library(gridExtra)

# https://aacrjournals.org/mct/article/16/9/1866/146539/A-Potential-Mechanism-for-ADC-Induced-Neutropenia
zhao2017 <- read.csv('data/Zhao2017_AGS5-mcMMAF.csv', header = TRUE) 

mod <- mread("model/neut_progenitor_adc_tox") 

allsim <- mod %>% init(promyelocyte = 3000) %>% mrgsim(end = 6) %>% as_tibble() %>% mutate(ID = 0) 

for (adcconc in zhao2017$ADC_nM) {
  sim <- mod %>% param(medium_ADC = adcconc) %>% init(promyelocyte = 3000) %>% mrgsim(end = 6) %>% as_tibble() 
  allsim <- rbind(allsim, 
                  sim %>% mutate(ID = adcconc) ) 
}

survival <- allsim %>% filter(time == 6) %>% mutate(survival_perc = totalcell/ first(totalcell) * 100)

p_survival <- ggplot() +
  geom_line(data = survival, aes(x = ID, y = survival_perc, col = "Simulated")) + 
  geom_point(data = zhao2017, aes(x = ADC_nM, y = survival_percent, col = "Zhao et al., 2017")) + 
  theme_bw() + theme(legend.position = "bottom") + 
  labs(x = "ADC concentration (nM)", y = "% survival", col = "", caption = "Generated by script/in_vitro_neut_tox.r") 

p_survival

ggsave("deliv/figure/adc-myelocyte-tox-in-vitro.png", plot = p_survival, width = 10, height = 10, units = "cm")

p_amp <-  ggplot(data = allsim %>% mutate(ID = round(ID, digits = 1)), aes(x = time, y = amp_myelocyte, group = as.factor(ID), col = as.factor(ID))) +
  geom_line() + 
  scale_y_continuous(trans = "log2") +
  theme_bw() + theme(legend.position = "bottom") + 
  labs(x = "Time (day)", y = "Amplification round of myelocytes", col = "ADC (nM)", caption = "Generated by script/in_vitro_neut_tox.r") 

p_amp

ggsave("deliv/figure/adc-myelocyte-tox-in-vitro-amp.png", plot = p_amp, width = 10, height = 10, units = "cm")
