# date: 10/10/24
# author: Yuezhe Li 
# purpose of this code: to test G-CSF treatment after HSCT

rm(list=ls())  #Clear out existing objects
gc()

library(here)
library(tidyverse)
library(mrgsolve)
library(gridExtra)
library(grid)
library(ggtext)

mod <- mread("model/human_mep_lymp_neut_gcsf") 

BW = 70
Vplasma = 3.1
MW_gcsf = 18.8E3

neutrophil_recovery_hsct_gcsf <- function(gcsf_dose, # ug/kg
                                          cd34dose, # cell count per kg
                                          gcsf_dose_route = "None", 
                                          ratioleft = 0.1, EndTime = 42){
  
  totalcd34 = cd34dose * BW 
  lthscinit = 1e-6 * totalcd34; 
  sthscinit = 1e-5 * totalcd34; 
  mppinit = 1e-3 * totalcd34;
  cmpinit = 1e-2 * totalcd34;
  clpinit = 1e-4 * totalcd34;
  boeinit = 5e-2 * totalcd34;
  
  ss <- mod  %>% init(LT0 = 1275) %>% mrgsim(end = 100) %>% as_tibble() %>% select(-c(ID, time)) %>% tail(n = 1)

  mod1 <- mod %>% 
    # conditioning (assuming lymphoid depletion)
    init(ss * ratioleft) %>%
    # add CD34+ infusion 
    init(LT0 = lthscinit + ss$LT0 * ratioleft) %>% 
    init(ST02 = sthscinit + ss$ST02 * ratioleft) %>% 
    init(MPP02 = mppinit + ss$MPP02 * ratioleft) %>% 
    init(CMP02 = cmpinit + ss$CMP02 * ratioleft) %>% 
    init(CLP0 = clpinit + ss$CLP0 * ratioleft) %>% 
    init(Boe0 = boeinit + ss$Boe0 * ratioleft) %>% 
    # restore RET, RBC, Hb
    init(RET0 = ss$RET0, RBC0 = ss$RBC0) %>%
    init(alpha_RET0 = ss$alpha_RET0, beta_RET0 = ss$beta_RET0, gamma_RET0 = ss$gamma_RET0, delta_RET0 = ss$delta_RET0) %>%
    init(alphabeta_RET0 = ss$alphabeta_RET0, alphagamma_RET0 = ss$alphagamma_RET0, alphadelta_RET0 = ss$alphadelta_RET0) %>%
    init(HbA_RET0 = ss$HbA_RET0, HbF_RET0 = ss$HbF_RET0, HbA2_RET0 = ss$HbA2_RET0) %>%
    init(alpha_RBC0 = ss$alpha_RBC0, beta_RBC0 = ss$beta_RBC0, gamma_RET0 = ss$gamma_RET0, delta_RET0 = ss$delta_RET0) %>%
    init(alphabeta_RBC0 = ss$alphabeta_RBC0, alphagamma_RBC0 = ss$alphagamma_RBC0, alphadelta_RBC0 = ss$alphadelta_RBC0) %>%
    init(HbA_RBC0 = ss$HbA_RBC0, HbF_RBC0 = ss$HbF_RBC0, HbA2_RBC0 = ss$HbA2_RBC0) %>%
    # restore neutrophil, G-CSF, and G-CSF receptor
    init(metamyelocyte = ss$metamyelocyte, bandcell = ss$bandcell, neutrophil_blood = ss$neutrophil_blood, neutrophil_pool = ss$neutrophil_pool) %>%
    init(gcsf = ss$gcsf, gcsfr = ss$gcsfr) %>%
    # restore MK cells and platelet
    init(platelet0 = ss$platelet0, TPO = ss$TPO) 
  
  # calculate gscf dose; from ug/kg -> pmol
  gcsf_dose_pmol = gcsf_dose * BW * 1E-6 / MW_gcsf * 1E12
  
  if (gcsf_dose_route == "iv"){
    # bolus IV dose of G-CSF
    sims <- mod1 %>% init(gcsf = ss$gcsf + gcsf_dose_pmol/Vplasma) %>% mrgsim(end = EndTime) %>% as_tibble() %>% select(-c(ID)) 
  }else if (gcsf_dose_route == "sc"){
    sims <- mod1 %>% init(gcsf_depot = gcsf_dose_pmol) %>% mrgsim(end = EndTime) %>% as_tibble() %>% select(-c(ID)) 
  } else{
    # gcsf_dose_route == "None"
    # simulation without G-CSF dosing
    sims <- mod1 %>% mrgsim(end = EndTime) %>% as_tibble() %>% select(-c(ID)) 
  }
  
  return(sims)
}

# no G-CSF treatment 
base1 <- neutrophil_recovery_hsct_gcsf(gcsf_dose = 0, cd34dose = 4.8E6)
base2 <- neutrophil_recovery_hsct_gcsf(gcsf_dose = 0, cd34dose = 6.4E6)

# https://pubmed.ncbi.nlm.nih.gov/11369630/
sc10 <- neutrophil_recovery_hsct_gcsf(gcsf_dose = 10, cd34dose = 4.8E6, gcsf_dose_route = "sc")
sc5 <- neutrophil_recovery_hsct_gcsf(gcsf_dose = 5, cd34dose = 4.8E6, gcsf_dose_route = "sc")

# https://pubmed.ncbi.nlm.nih.gov/11313683/
iv10 <- neutrophil_recovery_hsct_gcsf(gcsf_dose = 10, cd34dose = 6.4E6, gcsf_dose_route = "iv")
iv5 <- neutrophil_recovery_hsct_gcsf(gcsf_dose = 5, cd34dose = 6.4E6, gcsf_dose_route = "iv")

# visualization 
hsct_neut <- rbind(
  base1 %>% select(time, RBCconc, Bconc, Tconc, PLTconc, Neuconc, gcsf) %>% mutate(gcsfdose = "0 ug/kg", route = "SC"),
  sc5 %>%select(time, RBCconc, Bconc, Tconc, PLTconc, Neuconc, gcsf) %>% mutate(gcsfdose = "5 ug/kg", route = "SC"),
  sc10 %>%select(time, RBCconc, Bconc, Tconc, PLTconc, Neuconc, gcsf) %>% mutate(gcsfdose = "10 ug/kg", route = "SC"),
  base2 %>% select(time, RBCconc, Bconc, Tconc, PLTconc, Neuconc, gcsf) %>% mutate(gcsfdose = "0 ug/kg", route = "IV"), 
  iv5 %>% select(time, RBCconc, Bconc, Tconc, PLTconc, Neuconc, gcsf) %>% mutate(gcsfdose = "5 ug/kg", route = "IV"), 
  iv10 %>% select(time, RBCconc, Bconc, Tconc, PLTconc, Neuconc, gcsf) %>% mutate(gcsfdose = "10 ug/kg", route = "IV")
)

p_neut <- ggplot(data = hsct_neut, aes(x = time, y = Neuconc, col = gcsfdose)) + 
  geom_line() + 
  geom_hline(yintercept = 500, col = "red", linetype = 2, show.legend = FALSE) + 
  facet_wrap(~route, scales = "free_y") + 
  theme_bw() + 
  labs(x = "Time (day)", y = "Blood neutrophil count (#/uL)", col = "G-CSF dose", caption = "Generated by script/run_nuet_gscf_hsct.r") 

p_neut

p_gcsf <- ggplot(data = hsct_neut, aes(x = time, y = gcsf, col = gcsfdose)) + 
  geom_line() + 
  facet_wrap(~route, scales = "free_y") + 
  theme_bw() + 
  labs(x = "Time (day)", y = "plasma G-CSF (pM)", col = "G-CSF dose", caption = "Generated by script/run_nuet_gscf_hsct.r") 

p_gcsf

p_plt <- ggplot(data = hsct_neut, aes(x = time, y = PLTconc, col = gcsfdose)) + 
  geom_line() + 
  geom_hline(yintercept = 20E3, col = "red", linetype = 2, show.legend = FALSE) + 
  facet_wrap(~route) + 
  theme_bw() + 
  labs(x = "Time (day)", y = "blood PLT (#/uL)", col = "G-CSF dose", caption = "Generated by script/run_nuet_gscf_hsct.r") 

p_plt

ggsave("deliv/figure/dynamics_neutrophi_hsct_gcsf.png", plot = p_neut, width = 15, height = 7, units = "cm")
