# date: 10/2/24
# author: Yuezhe Li 
# purpose of this code: to test the GM -> neutrophil refinement of the model 

rm(list=ls())  #Clear out existing objects
gc()

library(here)
library(tidyverse)
library(mrgsolve)
library(gridExtra)
library(grid)
library(ggtext)

mod <- mread("model/human_ery_lymp_mk_neutrophil") 

# simulate mod steady state 
ss <- mod  %>% init(LT0 = 1275) %>% mrgsim(end = 365) %>% as_tibble() %>% 
  mutate(myelocyte = myelocyte01 + myelocyte02)

tail(ss, 1)["Neuconc"]

tail(ss, 1)["neutrophil_blood"]/tail(ss, 1)["neutrophil_pool"]

# time for myelocyte to transition to metamyelocyte
1/tail(ss, 1)["k_myelocyte2metamyelocyte"] * 24

tail(ss, 1)["myeloblast"]/tail(ss, 1)["myelocyte"]
tail(ss, 1)["promyelocyte"]/tail(ss, 1)["myelocyte"]
tail(ss, 1)["metamyelocyte"]/tail(ss, 1)["myelocyte"]
tail(ss, 1)["bandcell"]/tail(ss, 1)["myelocyte"]

# simulation of HSCT
pre_sim <- tail(ss, 1) %>% select(-c(ID, time))

# simulation of HSCT
BW = 70  # [kg]
totalcd34 = 5e6 * BW # https://www.astctjournal.org/article/S1083-8791(03)00696-7/fulltext
lthscinit = 1e-6 * totalcd34; 
sthscinit = 1e-5 * totalcd34; 
mppinit = 1e-3 * totalcd34;
cmpinit = 1e-2 * totalcd34;
clpinit = 1e-4 * totalcd34;
boeinit = 5e-2 * totalcd34;

ratioleft = 1 - 0.9

mod2 <- mod %>% init(pre_sim) %>% 
  init(pre_sim[,1:11] * ratioleft) %>% # progenitor in BM conditioning
  init(pre_sim[,34:37] * ratioleft) %>% # CLP and propreB conditioning
  init(pre_sim[,40:58] * ratioleft) %>% # proT conditioning
  init(pre_sim[,65:69] * ratioleft) %>% # myeloid progenitor conditioning
  init(pre_sim[,74:77] * ratioleft) %>% # megakaryocyte progenitor conditioning
  # HSCT
  init(LT0 = lthscinit + pre_sim$LT0 * ratioleft) %>% 
  init(ST02 = sthscinit + pre_sim$ST02 * ratioleft) %>% 
  init(MPP02 = mppinit + pre_sim$MPP02 * ratioleft) %>% 
  init(CMP02 = cmpinit + pre_sim$CMP02 * ratioleft) %>% 
  init(CLP0 = clpinit + pre_sim$CLP0 * ratioleft) %>% 
  init(Boe0 = boeinit + pre_sim$Boe0 * ratioleft) %>% 
  init(Bi0 = biinit + pre_sim$Bi0 * ratioleft) 

hsct <- mod2 %>% mrgsim(end = 40) %>% as_tibble() 

hsct %>% filter(Neuconc > 500) %>% View()

p_hsct <- ggplot(data = hsct, aes(x = time, y = Neuconc)) + 
  geom_line() + 
  geom_hline(yintercept = 500, col = "red", linetype = 2, show.legend = FALSE) + 
  theme_bw() + 
  labs(x = "Time (day)", y = "Blood neutrophil count (#/uL)", caption = "Generated by script/run_SteadyState_neutrophil.r") 

p_hsct

ggsave("deliv/figure/dynamics_neutrophi_hsct.png", plot = p_hsct, width = 10, height = 10, units = "cm")


# simulation of pulse labeling 
mod3 <- mod %>% init(pre_sim) %>% 
  param(kCMP2GMP = 0) %>% 
  init(metamyelocyte = 0, bandcell = 0, neutrophil_blood = 0, neutrophil_pool = 0, myelocyte02 = 0, myelocyte01 = 0)

pulse_labeling <- mod3 %>% mrgsim(end = 17, delta = 0.1) %>% as_tibble() %>% 
  mutate(relNeu = Neuconc/max(Neuconc))


# observed data from Figure 1, Perry et al., 1966; https://www.ncbi.nlm.nih.gov/pmc/articles/PMC292819/
perry1966 <- read.csv('data/Perry1966.csv', header = TRUE) 

p_pulse_labeling <- ggplot(data = pulse_labeling, aes(x = time, y = relNeu)) + 
  geom_line(aes(col = "Simulated")) + 
  geom_point(data = perry1966, aes(x = Time_day, y = relative_neutrophil, col = "Perry et al., 1966"), alpha = 0.4) + 
  theme_bw() + theme(legend.position = "bottom") + 
  labs(x = "Time (day)", y = "Normalized cell count", col = "", caption = "Generated by script/run_SteadyState_neutrophil.r") 

p_pulse_labeling

ggsave("deliv/figure/dynamics_neutrophi_pulselabeling.png", plot = p_pulse_labeling, width = 10, height = 10, units = "cm")
